/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    AInput: typeof import('ant-design-vue/es')['Input']
    Render: typeof import('./src/components/widget/input/render.vue')['default']
    Setting: typeof import('./src/components/setting.vue')['default']
    WidgetList: typeof import('./src/components/widgetList.vue')['default']
  }
}
